linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocyclo
    - dupl
    - goconst

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - dupl
  max-issues-per-linter: 0
  max-same-issues: 0

